[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pihole"
authors = [{name = "Cakir", email = "cakir@netmodule.com"}]
dynamic = ["version", "description"]
